/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lqtam
 */
public class HUD extends javax.swing.JFrame {

    /**
     * Creates new form HUD
     */
    public HUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        BoardBackground = new javax.swing.JPanel();
        Pos0 = new javax.swing.JPanel();
        Pos1 = new javax.swing.JPanel();
        Pos2 = new javax.swing.JPanel();
        Pos3 = new javax.swing.JPanel();
        Pos4 = new javax.swing.JPanel();
        Pos5 = new javax.swing.JPanel();
        Pos6 = new javax.swing.JPanel();
        Pos7 = new javax.swing.JPanel();
        Pos8 = new javax.swing.JPanel();
        WinnerDisplay = new javax.swing.JPanel();
        XWins = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        NoWinner = new javax.swing.JPanel();
        TIE = new javax.swing.JLabel();
        OWins = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        TTT = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(480, 720));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(480, 720));

        BoardBackground.setBackground(new java.awt.Color(0, 0, 0));
        BoardBackground.setPreferredSize(new java.awt.Dimension(456, 456));

        Pos0.setBackground(new java.awt.Color(255, 255, 255));
        Pos0.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos0MouseMoved(evt);
            }
        });
        Pos0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos0Layout = new javax.swing.GroupLayout(Pos0);
        Pos0.setLayout(Pos0Layout);
        Pos0Layout.setHorizontalGroup(
            Pos0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos0Layout.setVerticalGroup(
            Pos0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos1.setBackground(new java.awt.Color(255, 255, 255));
        Pos1.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos1MouseMoved(evt);
            }
        });
        Pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos1Layout = new javax.swing.GroupLayout(Pos1);
        Pos1.setLayout(Pos1Layout);
        Pos1Layout.setHorizontalGroup(
            Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos1Layout.setVerticalGroup(
            Pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos2.setBackground(new java.awt.Color(255, 255, 255));
        Pos2.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos2MouseMoved(evt);
            }
        });
        Pos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos2Layout = new javax.swing.GroupLayout(Pos2);
        Pos2.setLayout(Pos2Layout);
        Pos2Layout.setHorizontalGroup(
            Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos2Layout.setVerticalGroup(
            Pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos3.setBackground(new java.awt.Color(255, 255, 255));
        Pos3.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos3MouseMoved(evt);
            }
        });
        Pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos3Layout = new javax.swing.GroupLayout(Pos3);
        Pos3.setLayout(Pos3Layout);
        Pos3Layout.setHorizontalGroup(
            Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos3Layout.setVerticalGroup(
            Pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos4.setBackground(new java.awt.Color(255, 255, 255));
        Pos4.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos4MouseMoved(evt);
            }
        });
        Pos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos4Layout = new javax.swing.GroupLayout(Pos4);
        Pos4.setLayout(Pos4Layout);
        Pos4Layout.setHorizontalGroup(
            Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos4Layout.setVerticalGroup(
            Pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos5.setBackground(new java.awt.Color(255, 255, 255));
        Pos5.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos5MouseMoved(evt);
            }
        });
        Pos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos5Layout = new javax.swing.GroupLayout(Pos5);
        Pos5.setLayout(Pos5Layout);
        Pos5Layout.setHorizontalGroup(
            Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos5Layout.setVerticalGroup(
            Pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos6.setBackground(new java.awt.Color(255, 255, 255));
        Pos6.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos6MouseMoved(evt);
            }
        });
        Pos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos6Layout = new javax.swing.GroupLayout(Pos6);
        Pos6.setLayout(Pos6Layout);
        Pos6Layout.setHorizontalGroup(
            Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos6Layout.setVerticalGroup(
            Pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos7.setBackground(new java.awt.Color(255, 255, 255));
        Pos7.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos7MouseMoved(evt);
            }
        });
        Pos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos7Layout = new javax.swing.GroupLayout(Pos7);
        Pos7.setLayout(Pos7Layout);
        Pos7Layout.setHorizontalGroup(
            Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos7Layout.setVerticalGroup(
            Pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        Pos8.setBackground(new java.awt.Color(255, 255, 255));
        Pos8.setPreferredSize(new java.awt.Dimension(143, 143));
        Pos8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pos8MouseMoved(evt);
            }
        });
        Pos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pos8Layout = new javax.swing.GroupLayout(Pos8);
        Pos8.setLayout(Pos8Layout);
        Pos8Layout.setHorizontalGroup(
            Pos8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        Pos8Layout.setVerticalGroup(
            Pos8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BoardBackgroundLayout = new javax.swing.GroupLayout(BoardBackground);
        BoardBackground.setLayout(BoardBackgroundLayout);
        BoardBackgroundLayout.setHorizontalGroup(
            BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoardBackgroundLayout.createSequentialGroup()
                        .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Pos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoardBackgroundLayout.createSequentialGroup()
                                .addComponent(Pos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoardBackgroundLayout.createSequentialGroup()
                                .addComponent(Pos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BoardBackgroundLayout.createSequentialGroup()
                        .addComponent(Pos0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        BoardBackgroundLayout.setVerticalGroup(
            BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(BoardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        WinnerDisplay.setBackground(new java.awt.Color(0, 0, 0));
        WinnerDisplay.setForeground(new java.awt.Color(255, 255, 255));

        XWins.setBackground(new java.awt.Color(153, 153, 153));
        XWins.setPreferredSize(new java.awt.Dimension(143, 143));

        X.setBackground(new java.awt.Color(255, 255, 255));
        X.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic1.jpg"))); // NOI18N
        X.setLabelFor(XWins);
        X.setPreferredSize(new java.awt.Dimension(131, 131));

        javax.swing.GroupLayout XWinsLayout = new javax.swing.GroupLayout(XWins);
        XWins.setLayout(XWinsLayout);
        XWinsLayout.setHorizontalGroup(
            XWinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XWinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        XWinsLayout.setVerticalGroup(
            XWinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XWinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NoWinner.setBackground(new java.awt.Color(153, 153, 153));
        NoWinner.setPreferredSize(new java.awt.Dimension(143, 143));

        TIE.setBackground(new java.awt.Color(255, 255, 255));
        TIE.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        TIE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TIE.setText("TIE");
        TIE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TIE.setPreferredSize(new java.awt.Dimension(131, 131));

        javax.swing.GroupLayout NoWinnerLayout = new javax.swing.GroupLayout(NoWinner);
        NoWinner.setLayout(NoWinnerLayout);
        NoWinnerLayout.setHorizontalGroup(
            NoWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoWinnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TIE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NoWinnerLayout.setVerticalGroup(
            NoWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoWinnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TIE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        OWins.setBackground(new java.awt.Color(153, 153, 153));
        OWins.setPreferredSize(new java.awt.Dimension(143, 143));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic2.jpg"))); // NOI18N
        jLabel2.setLabelFor(OWins);
        jLabel2.setPreferredSize(new java.awt.Dimension(131, 131));

        javax.swing.GroupLayout OWinsLayout = new javax.swing.GroupLayout(OWins);
        OWins.setLayout(OWinsLayout);
        OWinsLayout.setHorizontalGroup(
            OWinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OWinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        OWinsLayout.setVerticalGroup(
            OWinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OWinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout WinnerDisplayLayout = new javax.swing.GroupLayout(WinnerDisplay);
        WinnerDisplay.setLayout(WinnerDisplayLayout);
        WinnerDisplayLayout.setHorizontalGroup(
            WinnerDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinnerDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        WinnerDisplayLayout.setVerticalGroup(
            WinnerDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WinnerDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(WinnerDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XWins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setPreferredSize(new java.awt.Dimension(140, 85));

        TTT.setBackground(new java.awt.Color(0, 0, 0));
        TTT.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TTT.setForeground(new java.awt.Color(255, 255, 255));
        TTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TTT.setLabelFor(TTT);
        TTT.setText("Triple T");
        TTT.setPreferredSize(new java.awt.Dimension(128, 73));

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Reset.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Reset.setText("RESET");
        Reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reset.setPreferredSize(new java.awt.Dimension(140, 85));
        Reset.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ResetMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BoardBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WinnerDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WinnerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoardBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pos0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos0MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Pos0MouseMoved

    private void Pos1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos1MouseMoved

    private void Pos2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos2MouseMoved

    private void Pos3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos3MouseMoved

    private void Pos4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos4MouseMoved

    private void Pos5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos5MouseMoved

    private void Pos6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos6MouseClicked

    private void Pos6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos6MouseMoved

    private void Pos7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos7MouseClicked

    private void Pos7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos7MouseMoved

    private void Pos8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos8MouseClicked

    private void Pos8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos8MouseMoved

    private void Pos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos5MouseClicked

    private void Pos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos4MouseClicked

    private void Pos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos3MouseClicked

    private void Pos0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos0MouseClicked

    private void Pos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos1MouseClicked

    private void Pos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos2MouseClicked

    private void ResetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ResetMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BoardBackground;
    private javax.swing.JPanel NoWinner;
    private javax.swing.JPanel OWins;
    private javax.swing.JPanel Pos0;
    private javax.swing.JPanel Pos1;
    private javax.swing.JPanel Pos2;
    private javax.swing.JPanel Pos3;
    private javax.swing.JPanel Pos4;
    private javax.swing.JPanel Pos5;
    private javax.swing.JPanel Pos6;
    private javax.swing.JPanel Pos7;
    private javax.swing.JPanel Pos8;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel TIE;
    private javax.swing.JLabel TTT;
    private javax.swing.JPanel Title;
    private javax.swing.JPanel WinnerDisplay;
    private javax.swing.JLabel X;
    private javax.swing.JPanel XWins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
