/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author lqtam
 */
public class HUD extends JFrame {
    /**
     *
     */
    protected Board board;
    /**
     *
     */
    protected String player;
    /**
     * Creates new form HUD
     */
    public HUD() {
        this.player = "X";
        this.board = new Board();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Background = new JPanel();
        Title = new JLabel();
        Board = new JPanel();
        Positions = new JButton[9];

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(634, 532));

        Background.setBackground(new Color(0, 0, 0));
        Background.setForeground(new Color(255, 255, 255));

        Title.setBackground(new Color(0, 0, 0));
        Title.setFont(new Font("Times New Roman", 3, 48)); // NOI18N
        Title.setForeground(new Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Tic-Tac-Toe");

        Board.setBackground(new java.awt.Color(255, 255, 255));
        Board.setPreferredSize(new java.awt.Dimension(446, 446));
        Board.setLayout(new java.awt.GridLayout(3, 3, 12, 12));

        for (int i = 0; i < 9; i++) {
            final int pos = i;
            Positions[pos] = new JButton(" ");
            Positions[pos].setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
            Positions[pos].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            Positions[pos].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    PositionActionPerformed(pos, evt);
                }
            });
            Board.add(Positions[pos]);
        }

        GroupLayout BackgroundLayout = new GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(Board, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(Board, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>                        

    private void PositionActionPerformed(int pos, java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if (board.validMove(pos)) {
            board.move(pos, player);
            Positions[pos].setText(player);

            if (player.equals("X")) {
                player = "O";
            } else {
                player = "X";
            }

            switch (board.checkWin()) {
                case 1 -> {
                    JOptionPane.showMessageDialog(this, "X WINS! GAME OVER YEAH!!!");
                    System.exit(0);
                }
                case 2 -> {
                    JOptionPane.showMessageDialog(this, "O WINS! GAME OVER YEAH!!!");
                    System.exit(0);
                }
                case 3 -> {
                    JOptionPane.showMessageDialog(this, "A DRAW! GAME OVER YEAH!!!");
                    System.exit(0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid move.");
        }
    }//GEN-LAST:event_Pos0ActionPerformed

    // Variables declaration - do not modify                     
    protected JPanel Background;
    protected JButton[] Positions;
    protected JLabel Title;
    protected JPanel Board;
    // End of variables declaration                   
}
